name: Reusable Build & Deploy Workflow

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      aks_name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  build_and_push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: mvn clean package -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  security_scan:
    name: security-scan
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Run Trivy
        run: trivy fs . || true
      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  deploy:
    name: deploy-to-production
    runs-on: ubuntu-latest
    needs: [build_and_push, security_scan]
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ inputs.resource_group }} \
            --name ${{ inputs.aks_name }} \
            --overwrite-existing --admin
      - name: Deploy to AKS
        run: kubectl apply -f ds.yml --validate=false
